# permissions for end users to edit keptnscheduledexecs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keptnscheduledexec-editor-role
rules:
- apiGroups:
  - keptn.sh
  resources:
  - keptnscheduledexecs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keptn.sh
  resources:
  - keptnscheduledexecs/status
  verbs:
  - get
