# permissions for end users to view keptnsequenceexecutions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keptnsequenceexecution-viewer-role
rules:
- apiGroups:
  - keptn.sh
  resources:
  - keptnsequenceexecutions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - keptn.sh
  resources:
  - keptnsequenceexecutions/status
  verbs:
  - get
