# permissions for end users to view keptnservicedeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keptnservicedeployment-viewer-role
rules:
- apiGroups:
  - keptn.sh
  resources:
  - keptnservicedeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - keptn.sh
  resources:
  - keptnservicedeployments/status
  verbs:
  - get
