# permissions for end users to view keptndeploymentcontexts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keptndeploymentcontext-viewer-role
rules:
- apiGroups:
  - keptn.sh
  resources:
  - keptndeploymentcontexts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - keptn.sh
  resources:
  - keptndeploymentcontexts/status
  verbs:
  - get
