# permissions for end users to edit keptnsequenceexecutions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keptnsequenceexecution-editor-role
rules:
- apiGroups:
  - keptn.sh
  resources:
  - keptnsequenceexecutions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keptn.sh
  resources:
  - keptnsequenceexecutions/status
  verbs:
  - get
