# permissions for end users to view keptnshipyards.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keptnshipyard-viewer-role
rules:
- apiGroups:
  - keptn.sh
  resources:
  - keptnshipyards
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - keptn.sh
  resources:
  - keptnshipyards/status
  verbs:
  - get
