# permissions for end users to edit keptnsequences.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keptnsequence-editor-role
rules:
- apiGroups:
  - keptn.sh
  resources:
  - keptnsequences
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keptn.sh
  resources:
  - keptnsequences/status
  verbs:
  - get
