# permissions for end users to edit keptnstages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keptnstage-editor-role
rules:
- apiGroups:
  - keptn.sh
  resources:
  - keptnstages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keptn.sh
  resources:
  - keptnstages/status
  verbs:
  - get
