apiVersion: v1
data:
  RSA_PRIVATE_KEY: {{ .Values.global.rsaSecret.privateBase64 | b64enc }}
kind: Secret
metadata:
  name: {{ .Values.global.rsaSecret.secretName }}
  namespace: {{ .Release.Namespace }}