apiVersion: "keptn.sh/v1"
kind: "KeptnGitRepository"
metadata:
  name: "upstream"
spec:
  repository: "https://github.com/thschue/inno_day_code"
  username: thschue
  password: "rsa:fnCuAWbA9VZAn5AQrxINp9ykpmaXgwF6HX1XYCOJ2AOSTxS8tBbADT8eBR47tpK/ab7IKGzX4FD1p3juwt+1WIFa9Jb7mdP2eI6PWJOvpt+jmXSXdEIprU1q9wRzkz1gPEz24LyKxJL+shmINji2k6jj0tgo/IkAyfttDFqny8XKCtNxfOVbkpDlhBIxND5jwHzRJm+zoI4L1OPiJaSyp2t3ry7HWZjWFqjkpC9pBNd7WQ+611XuG5727FfUbbb7hJHZx2CQVUUXurxmKNZI8m3459vB8l5aAeihBGtW/RqGf/5Hq+yVQFa+e4ja4ivGgPGocH0sWY2x6yvk4iL6YQ=="

