apiVersion: "keptn.sh/v1"
kind: "KeptnSequence"
metadata:
  name: "podtatohead-delivery-dev"
spec:
  sequence:
    name: "artifact-delivery"
    tasks:
    - name: "promotion"
    - name: "deployment"
      properties:
        deploymentstrategy: "user_managed"
    - name: "test"
      properties:
        teststrategy: "functional"

---
apiVersion: "keptn.sh/v1"
kind: "KeptnSequence"
metadata:
  name: "podtatohead-delivery-hardening"
spec:
  sequence:
      name: "artifact-delivery"
      triggeredOn:
        - event: "dev.artifact-delivery.finished"
      tasks:
        - name: approval
          properties:
            pass: manual
            warning: manual
        - name: "promotion"
        - name: "deployment"
          properties:
            deploymentstrategy: "user_managed"
        - name: "test"
          properties:
            teststrategy: "functional"

---
apiVersion: "keptn.sh/v1"
kind: "KeptnSequence"
metadata:
  name: "podtatohead-delivery-production"
spec:
  sequence:
      name: "artifact-delivery"
      triggeredOn:
        - event: "hardening.artifact-delivery.finished"
      tasks:
        - name: approval
          properties:
            pass: manual
            warning: manual
        - name: "promotion"
        - name: "deployment"
          properties:
            deploymentstrategy: "user_managed"
        - name: "test"
          properties:
            teststrategy: "functional"
