gitops-operator:
  enabled: true
  image: keptnsandbox/gitops-operator:0.0.6-dev-PR-18

keptn-operator:
  enabled: true
  image: keptnsandbox/keptn-operator:0.0.6-dev-PR-18

promotion-service:
  image: keptnsandbox/promotion-service:0.0.6-dev-PR-18

