gitops-operator:
  enabled: true
  image: keptnsandbox/gitops-gitops-operator:latest

keptn-operator:
  enabled: true
  image: keptnsandbox/gitops-keptn-operator:latest

promotion-service:
  image: keptnsandbox/gitops-promotion-service:latest