image: keptnsandbox/gitops-gitops-operator:latest
secret_encryption_private_key: ""

serviceAccount:
  create: true                               # Enables the service account creation
  annotations: {}                            # Annotations to add to the service account
  name: ""                                   # The name of the service account to use.
