# permissions for end users to edit keptngitrepositories.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keptngitrepository-editor-role
rules:
- apiGroups:
  - keptn.sh
  resources:
  - keptngitrepositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keptn.sh
  resources:
  - keptngitrepositories/status
  verbs:
  - get
