# permissions for end users to view keptngitrepositories.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keptngitrepository-viewer-role
rules:
- apiGroups:
  - keptn.sh
  resources:
  - keptngitrepositories
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - keptn.sh
  resources:
  - keptngitrepositories/status
  verbs:
  - get
