
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - update
- apiGroups:
  - keptn.sh
  resources:
  - keptngitrepositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keptn.sh
  resources:
  - keptngitrepositories/finalizers
  verbs:
  - update
- apiGroups:
  - keptn.sh
  resources:
  - keptngitrepositories/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - keptn.sh
  resources:
  - keptninstances
  verbs:
  - get
  - list
- apiGroups:
  - keptn.sh
  resources:
  - keptninstances/
  verbs:
  - create
  - get
  - list
  - update
- apiGroups:
  - keptn.sh
  resources:
  - keptnprojects
  verbs:
  - get
  - list
- apiGroups:
  - keptn.sh
  resources:
  - keptnprojects/
  verbs:
  - create
  - get
  - list
  - update
- apiGroups:
  - keptn.sh
  resources:
  - keptnscheduledexecution/
  verbs:
  - create
  - get
  - list
  - update
- apiGroups:
  - keptn.sh
  resources:
  - keptnsequenceexecution/
  verbs:
  - create
  - get
  - list
  - update
- apiGroups:
  - keptn.sh
  resources:
  - keptnsequences
  verbs:
  - get
  - list
- apiGroups:
  - keptn.sh
  resources:
  - keptnsequences/
  verbs:
  - create
  - get
  - list
  - update
- apiGroups:
  - keptn.sh
  resources:
  - keptnservicedeployment/
  verbs:
  - create
  - get
  - list
  - update
- apiGroups:
  - keptn.sh
  resources:
  - keptnservices/
  verbs:
  - create
  - get
  - list
  - update
- apiGroups:
  - keptn.sh
  resources:
  - keptnstage/
  verbs:
  - create
  - get
  - list
  - update
