---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: keptn-operator
  name: keptn-operator
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: keptn-operator
  template:
    metadata:
      labels:
        control-plane: keptn-operator
    spec:
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
          protocol: TCP
      - args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        - --leader-elect
        command:
        - /manager
        image: {{ .Values.image }}
          {{ if .Values.global.rsaSecret.secretName }}
        envFrom:
          - secretRef:
              name: .Values.global.rsaSecret.secretName
              {{ else }}
        env:
          {{ if .Values.secret_encryption_private_key }}
          - name: RSA_PRIVATE_KEY
            value: {{ .Values.secret_encryption_private_key }}
            {{ end }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 20Mi
        securityContext:
          allowPrivilegeEscalation: false
      securityContext:
        runAsNonRoot: true
      serviceAccountName: {{ include "gitops-operator.serviceAccountName" . }}
      terminationGracePeriodSeconds: 10
