name: reviewdog
on: [pull_request]

jobs:
  reviewdog:
    name: reviewdog
    runs-on: ubuntu-latest

    strategy:
      matrix:
        services: ["keptn-operator", "gitops-operator", "promotion-service"]

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
        id: go

      - name: Check out code.
        uses: actions/checkout@v1

      - name: Install linters
        run: '( mkdir linters && cd linters && go get golang.org/x/lint/golint )'

      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory:  ${{ matrix.services }}
        run: |
          reviewdog -reporter=github-pr-review